Bland-Altman Plots for the Reliability Module
jasp-stats/jaspReliability pull request #111
Opened 2022-06-20 11:17 UTC by foger3

Handles part of the request: https://github.com/jasp-stats/jasp-issues/issues/494

2022-06-21 10:50 UTC, juliuspf commented
Hi @foger3 thank you for making the plot available in JASP. Is there a particular reason why the plot is part of the intraclass correlation analysis? It is used for comparing two measurements, right? And usually the ICCs compare more than two measurement/ratings. Having said that, I am uncertain if it would better be within rater agreement, since it is not necessarily comparing raters but more generally measurements, and thus could confuse people. It could also get its own analysis tab underneath reliability, or we make a completely new ribbon for "agreement" given that there are more feature requests concerning that (https://github.com/jasp-stats/jasp-issues/issues/1755). Maybe @AlexanderLyNL or @vandenman have some input...

2022-06-22 07:21 UTC, Kucharssim commented
Yes, we had a discussion with @foger3 about this a while ago, it indeed did not seem like this plot fits into any particular analysis... I am not sure what was the main reason to put it under a separate section in the ICC and not rater agreement, but this was definitely a factor:

> For the rater agreement analysis the data is read in as factors, which will not work with the plot

----

>My preference for now would be number 3, since the plot does not depend on any results from any of the other analyses.

Fair point, but making a whole new separate analysis just for one plot seems a bit odd, even though it does remove some of the awkwardness of using it within an analysis that does not really correspond to it. 

Another alternative would be to put it into descriptives? I am not sure whether it's good to make the descriptives more bloated than they already are for such a specialised plot, though.

> make a new ribbon "Agreement" distinct from "Reliability" and add the ICC, rater agreement, and Bland-Altman plot to it given that there are more feature requests concerning that

Not a bad idea, but not something we should do right now, I think... Once we support that one module can show as separate icons in the ribbon, we could do it that way (see discussion in https://github.com/jasp-stats/INTERNAL-jasp/issues/1812)

2022-06-24 12:20 UTC, Kucharssim commented
> you can only use the variables of a data set in the plot when they have been added to the ICC analysis

I see your point. We could do by removing the `source` in the AvailableVariablesList component which will allow to use any variables, not only those that we compute the ICC for... However, yeah then it's kind of pointless to have it in the ICC in the first place. I think you changed my mind a little bit, perhaps it would be better to just make it a separate analysis...

2022-06-27 09:38 UTC, juliuspf commented
I can move this into a separate analysis if that is okay with @foger3. I am not sure if I have permissions to make changes to this PR though... in the past this has often not worked.

2022-08-25 08:43 UTC, Kucharssim requested changes
Looks good, the only thing to do to finish this would be to remove this functionality from the ICC analysis, right? Otherwise the functionality is duplicated.

2022-08-25 12:18 UTC, Kucharssim requested changes

2022-08-25 12:18 UTC, Kucharssim commented on R/intraclassCorrelation.R
> +  .descriptivesBlandAltmanTable(jaspResults, dataset, options)
This also needs to go, right?

2022-08-25 13:25 UTC, Kucharssim approved these changes
Great! Thanks @juliuspf for taking over the PR!

2022-08-25 13:26 UTC, merged