New analysis: standard errors of measurement
jasp-stats/jaspReliability pull request #210
Opened 2024-08-07 07:28 UTC by juliuspfadt

this adds standard error of measurement estimates. 
I need the PR for the submission of a tutorial paper.

2024-08-23 08:15 UTC, vandenman commented on tests/testthat/test-standardErrorOfMeasurement.R
> +options <- analysisOptions("standardErrorOfMeasurement")
please change this to directly specify the options list, jaspTools cannot handle this.

2024-08-23 08:16 UTC, vandenman commented on R/standardErrorOfMeasurement.R
> +
```suggestion
```

2024-08-23 09:36 UTC, vandenman commented on tests/testthat/test-standardErrorOfMeasurement.R
> +  )
should be
```suggestion
  variables = c("asrm_1", "asrm_2", "asrm_3", "asrm_4", "asrm_5"),
  variables.types = c("ordinal", "ordinal", "ordinal", "ordinal", "ordinal")
```

2024-08-23 11:18 UTC, juliuspfadt commented
I changed the tests a bit, however, I cannot make tests from the test-file. It always gives an error when `makeTests=TRUE`

2024-08-26 14:19 UTC, vandenman requested changes
- The analysis does not like `contExpon`:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/84d41744-5d2c-4a30-9670-4bfc77f8bdd3">

or continuous variables in the debug dataset in general:

<img width="709" alt="image" src="https://github.com/user-attachments/assets/0c223479-cef5-4a58-aeed-f004411b3b36">

<img width="898" alt="image" src="https://github.com/user-attachments/assets/87d72118-8331-4a2e-a724-cfe99e6fdfd2">

- Is there a better name than "combined plot"? 

Using the dataset below I noticed that:

- Mollenkopf-Feldt is empty for some reason:

<img width="831" alt="image" src="https://github.com/user-attachments/assets/a4ff1ed5-2851-4f3e-9825-fa425e027ef6">

perhaps add a footnote?

- The 2PL plot looks incorrect (but that could just be me)

![image](https://github.com/user-attachments/assets/343ae731-6640-418d-ac6c-ce99db5905ec)


[reliability_pr_210_debug.jasp.zip](https://github.com/user-attachments/files/16749831/reliability_pr_210_debug.jasp.zip)

2024-08-27 08:32 UTC, juliuspfadt commented
hmm, well continuous variables are not allowed. It's easy to force an ordinal variable to be continuous but not the other way around. We have allowed columns, but that is by now only a suggestion. I dont know how to remedy this. If allowed columns would be strict...

2024-08-27 09:24 UTC, juliuspfadt commented
Have you found a way to create the unit tests?

2024-09-03 09:38 UTC, juliuspfadt commented
Alright, thanks. I have changed the levels and the tests. Can you review again?

2024-09-23 14:30 UTC, juliuspfadt commented
I checked the pot again, and now it looks like this: 
![Screenshot 2024-09-23 at 15 33 08](https://github.com/user-attachments/assets/05ef2e18-5cda-4665-bb27-fd73f6ce964b)
I checked the numbers in R and I think the issue is that with that data the IRT model yields some weird results; it also takes more iterations than "usual". I am inclined to leave it as is

2024-09-24 07:27 UTC, vandenman approved these changes

2024-09-24 07:29 UTC, merged

2024-09-24 07:30 UTC, vandenman commented
Looks good! Do you think this is a good point to maybe start a `NEWS.md` file for this module? See e.g., [here](https://github.com/r-lib/ragg/blob/main/NEWS.md) for an example, this does not need to be long and the goal is to facilitate the automatic generation of release notes. We want to do this for a longer time, but I'd first like to try it out with one or two modules to see how well it goes (see also https://github.com/jasp-stats/INTERNAL-jasp/issues/1913).