Adds tests, small improvements in display of tables and plots, fix of KLD issue
jasp-stats/jaspReliability pull request #5
Opened 2020-08-19 15:57 UTC by juliuspf

fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1026

2020-09-01 12:14 UTC, TimKDJ commented
Is this PR up-to-date with https://github.com/jasp-stats/jasp-desktop/pull/4249?

2020-09-01 12:31 UTC, juliuspf commented
What do you mean by that?

2020-09-01 12:33 UTC, TimKDJ commented
Are all the changes you made in the jasp-desktop pull request (e.g., review comment changes), included in this PR?

2020-09-01 12:34 UTC, juliuspf commented
Ah, ja! The R-files are exactly the same

2020-09-01 12:34 UTC, juliuspf commented
Just the tests are new here

2020-09-04 07:37 UTC, TimKDJ requested changes
Looks good, just minor changes required

2020-09-04 07:37 UTC, TimKDJ commented on .travis.yml
> +r_github_packages: jasp-stats/jaspTools
Could you use https://github.com/jasp-stats/jasp-desktop/blob/stable/JASP-Tests/README.md#travisyml?

2020-09-04 07:37 UTC, TimKDJ commented on DESCRIPTION
> -Imports: Rdpack, Bayesrel, Rcsdp (>= 0.1.57)
These don't look like changes we necessarily want. Are they made on purpose?

2020-09-04 07:37 UTC, TimKDJ commented on tests/testthat/test.csv
> +,contNormal,contGamma,contBinom,contExpon,contWide,contNarrow,contOutlier,contcor1,contcor2,facGender,facExperim,facFive,facFifty,facOutlier,debString,debMiss1,debMiss30,debMiss80,debMiss99,debBinMis
This file is now shipped with `jaspTools` so you don't need to include it

2020-09-23 13:22 UTC, TimKDJ approved these changes

2020-09-23 13:22 UTC, merged